### ISSUE TITLE
Trying to pack behind the windrower (last Patch)

### ISSUE THREAD

**Issue by Vanquish081** [DeckerMMIV/FarmSim_Mod_FollowMe#61] opened 2023-04-06 17:43 UTC
``` 2023-04-06 19:36 Game saved successfully.
2023-04-06 19:37 dataS/character/humans/npc/pedestrians/generic/npcCommon02_f.i3d (38.91 ms)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Lua memory usage has reached 308322 KB; this is a dangerous level for PS4.
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
2023-04-06 19:38 Error: Running LUA method 'update'.
dataS/scripts/vehicles/Vehicle.lua(2685) : attempt to index field 'targetObject' (a number value)
...
...
....
etc....
etc....

**Comment by DeckerMMIV** [comment] 2023-05-29 12:45
No mention of 'Follow Me' in the snippet from the log.txt, so probably not caused by 'Follow Me'.

Therefore closing this ticket, as there is not much to go after, nor any description of "how to reproduce the failure/bug".

However, since I myself discovered a game breaking bug, caused by 'Follow Me' when using it on a self-propelled slurry spreader, then maybe that could have been something of what you experienced? - A version 1.3.0.0 of 'Follow Me' that solves the game breaking bug when using self-propelled slurry spreader, have been submitted to GIANTS Software's ModHub and awaits verification.

**Closed by DeckerMMIV** 2023-05-29 12:45 UTC
